import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Mainbg from '../components/Mainbg'
import Nav from '../components/Nav'
import A from '../components/A'
import { Gallery } from '../components/Gallery'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Gallery />
     
    </div>
  )
}

export default Home
